✚ We support Gradle >= 6.3
In Gradle 6.2, coroutines fail with this error:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':refreshVersions'.
Caused by: java.lang.NoClassDefFoundError: kotlin/coroutines/AbstractCoroutineContextKey

https://gradle.com/s/shp7hbtd3i3ii

How I tested the thing:

```
$ echo "Install SDK man"
$ open https://sdkman.io/
$ sdk install gradle 6.2
$ sdk use gradle 6.2
$ cd sample-kotlin
$ gradle help
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/jmfayard/IdeaProjects/refreshVersions/sample-kotlin/settings.gradle.kts' line: 28

* What went wrong:
The plugin "de.fayard.refreshVersions" only works with Gradle 6.3 and above.
```